apiVersion: v1
kind: ConfigMap
metadata:
  name: nsx-ncp-config
  namespace: nsx-system
  labels:
    version: v1
data:
  ncp.ini: |
    [DEFAULT]
    [coe]
    cluster = k8s-cluster1
    nsxlib_loglevel=INFO
    [ha]
    [k8s]
    apiserver_host_ip = 10.1.1.129
    apiserver_host_port = 6443
    ca_file = /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
    client_token_file = /var/run/secrets/kubernetes.io/serviceaccount/token
    [nsx_v3]
    nsx_api_managers = nsxmgr-01a.corp.local
    nsx_api_user = admin
    nsx_api_password = VMware1!
    insecure = True
    subnet_prefix = 28
    use_native_loadbalancer = True
    pool_algorithm = 'ROUND_ROBIN'
    service_size = 'SMALL'
    virtual_servers_per_lbs = 10
    tier0_router = Tier0_LR
    overlay_tz = TZ
    container_ip_blocks = e77b1435-54af-43bc-8045-9a22b8e3bdf9
    external_ip_pools = b1b80f47-97de-4d1a-81d8-93bf6c98d613
    top_firewall_section_marker = aedcc7ec-ccf1-44ee-a66e-b371371b87e9
    bottom_firewall_section_marker = 001fd432-cd48-4339-926e-d692032cb0e7
---
apiVersion: v1
kind: ReplicationController
metadata:
  name: nsx-ncp
  namespace: nsx-system
  labels:
    tier: nsx-networking
    component: nsx-ncp
    version: v1
spec:
  replicas: 1
  template:
    metadata:
      labels:
        tier: nsx-networking
        component: nsx-ncp
        version: v1
    spec:
      hostNetwork: true
      serviceAccountName: ncp-svc-account
      containers:
        - name: nsx-ncp
          image: harbor-tenant-01.sg.lab/singapore-infra/nsx-ncp:2.3.0
          imagePullPolicy: IfNotPresent
          env:
            - name: NCP_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: NCP_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          livenessProbe:
            exec:
              command:
                - /bin/sh
                - -c
                - check_pod_liveness nsx-ncp
            initialDelaySeconds: 5
            timeoutSeconds: 5
            periodSeconds: 10
            failureThreshold: 5
          volumeMounts:
          - name: config-volume
            mountPath: /etc/nsx-ujo/ncp.ini
            subPath: ncp.ini
            readOnly: true
      volumes:
        - name: config-volume
          configMap:
            name: nsx-ncp-config